name: Python application

on:
  push:
    branches:
      - main  # Runs on pushes to the "main" branch
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu version for the runner

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Install dependencies (assuming you have a requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have this file with necessary dependencies

    # Run tests (assuming you have tests in a "tests" directory)
    - name: Run tests
      run: |
        pytest tests  # You can modify this command to run your test suite
